export const SET_DYNAMICROUTE_MUTATION = 'SET_DYNAMICROUTE_MUTAION'
export const SET_DYNAMICROUTE_ACTION = 'SET_DYNAMICROUTE_ACTION'
export const DEL_DYNAMICROUTE_MUTATION = 'DEL_DYNAMICROUTE_MUTATION'
export const DEL_DYNAMICROUTE_ACTION = 'DEL_DYNAMICROUTE_ACTION'