export const SET_USERINFO_MUTATION = 'SET_USERINFO_MUTATION'
export const DEL_USERINFO_MUTATION = 'DEL_USERINFO_MUTATION'
export const SET_USERINFO_ACTION = 'SET_USERINFO_ACTION'
export const DEL_USERINFO_ACTION = 'DEL_USERINFO_ACTION'